ENV = "dev"
ELASTICSEARCH_HOST_URL =
HEADER = {"Content-Type": "application/json"}

DOUBLE_LINE = "\n\n"
TABLES_DIR = "tables"


SEARCH_TERMS = [
    "Lemonade",
    "Cannabis",
    "Smart Home",
    "Autonomous vehicles",
    "Agtech",
    "artificial intelligence",
    "Blockchain",
    "fintech",
    "stripe",
    "google",
    "Insurtech",
    "Healthcare",
    "AI",
    "Insurance",
    "real estate",
    "cannabis",
    "retail",
    "amazon",
    "uber",
    "Digital Health",
    "cybersecurity",
    "Regtech",
    "payments",
    "iot",
    "food",
    "facebook",
    "5g",
    "beauty",
    "Agtech",
    "market map",
    "venture capital",
    "construction",
    "logistics",
    "smart home",
    "robotics",
    "mobility",
    "wework",
    "3d printing",
    "HR tech",
    "real estate tech",
    "edtech",
    "corporate venture capital",
    "esports",
    "agriculture",
    "wellness",
    "softbank",
    "china",
    "HEALTH",
    "ecommerce",
    "fintech 250",
    "Lemonade",
    "Andreessen Horowitz",
    "banking as a service",
    # TODO:
    # ( machine learning OR artificial intelligence ) AND ( sales OR customer support )
    # ( health OR healthcare OR patient OR doctor OR medical ) AND Facebook
    # timeline AND artificial intelligence
    # Artificial Intelligence OR Machine Learning
    # regtech AND security
    # insurtech OR insurance tech
]


SAYT_NAMES = [
    "21 Net",
    "Low Fi",
    "ID bio",
    "In Re",
    "SA VA",
    "I Met",
    "MTS",
    "12 FM",
    "C & M",
    "J Play",
    "IBT Rx",
    "VR Nam",
    "DH Lab",
    "TV One",
    "M Cash",
    "MWWPR",
    "V APP",
    "LU LU",
    "DS SM",
    "BW Pay",
    "HSE 24",
    "SKU IQ",
    "Eris 4",
    "Biopta",
    "Mtd",
    "IVCi",
    "UCL",
    "Chi-Med",
    "ADMETRx",
    "Tripos",
    "Kerr",
    "Aegion",
    "Federos",
    "Pilat",
    "ThinkMTV",
    "Proact",
    "Tapad",
    "Ovitz",
    "StormWind",
    "Compiere",
    "UC Davis",
    "Angelica",
    "Centocor",
    "AdPepper",
    "NeoSpire",
    "Bezeq",
    "D. E. Shaw",
    "O Cigarette",
    "Broadpoint",
    "Protegrity",
    "Batzu Media",
    "MairDumont",
    "Undertone",
    "Phandeeyar",
    "GMI",
    "POP",
    "ORC",
    "AR New York",
    "Zignal Labs",
    "Tsavo",
    "Zyvex",
    "Redbadge",
    "Parnell",
    "Dako",
    "Morphochem",
    "Ethos Water",
    "Meal Magnet",
    "Tippt Media",
    "Ground Labs",
    "BroadLogic",
    "Blue Medora",
    "IXI Mobile",
    "Awesome API",
    "SurgiQuest",
    "Multi Touch",
    "Chase Doors",
    "HUB STUDIOS",
    "Truly Yours",
    "Frank Deals",
    "Idee Fabrik",
    "Flip Pocket",
    "AGP Miami",
    "Televisa",
    "MilcomTech",
    "Angelsoft",
    "Finch Paper",
    "Thiel Audio",
    "Jarvis Labs",
    "IDEAg Group",
    "DJ Nitrogen",
    "Onmobile",
    "Device Pipe",
    "LANDR Audio",
    "Eclipx",
    "Mobile Flow",
    "Med for all",
    "Mean Turtle",
    "Soul Sprout",
    "Gwynnie Bee",
    "Care Thread",
    "Hab Housing",
    "TVC Skyshop",
    "Duet Health",
    "Play Crafts",
    "COR Systems",
    "CUSTOpharm",
    "Liquid Labs",
    "JM TechWare",
    "Value Place",
    "Pluto Media",
    "DB Networks",
    "Gray Routes",
    "One Jackson",
    "Dexter Axle",
    "food direkt",
    "HPC Systems",
    "Mayi Duanzu",
    "NovoJuris",
    "Conservice",
    "Biochar Now",
    "Drink Tanks",
    "Exam Design",
    "Noble Touch",
    "Monkey Gods",
    "Europa Labs",
    "Vermont Soy",
    "The Taploid",
    "ENB Science",
    "DKB Fitness",
    "Carre Blanc",
    "Akila Media",
    "CNC Screens",
    "Snap Brands",
    "Member Ally",
    "Hill Manors",
    "SVG Capital",
    "GS Ventures",
    "Point Reach",
    "My Jamb Man",
    "G3 Services",
    "Myne Health",
    "Game Karmic",
    "Pocket Menu",
    "GPS Connect",
    "Munch On Me",
    "EZ Freeware",
    "Nomos Media",
    "M.E. Energy",
    "Study Cloud",
    "Tip or Skip",
    "Edge Driven",
    "Genala Banc",
    "Urban Cargo",
    "Seps Pharma",
    "Lifebox JSC",
    "EMS YAZILIM",
    "Tiny Hearts",
    "Telepath UK",
    "Eletson Gas",
    "DHC Finance",
    "KDM Trading",
    "Ondal Group",
    "Mitre Media",
    "Roll Filter",
    "Power Fuels",
    "Wind Mobile",
    "Vero Energy",
    "CI Holdings",
    "B-29 Energy",
    "908 Devices",
    "Virtual DBS",
    "Clear Books",
    "8020 Select",
    "Beefy Media",
    "Ticket Cake",
    "SMK project",
    "ZOO Digital",
    "Spend Radar",
    "NC Dynamics",
    "Piano Media",
    "Third Sight",
    "Zach Browne",
    "QWeMA Group",
    "Dev Xfactor",
    "Soshi Games",
    "Dynamic B2B",
    "LoveLive TV",
    "CABO Yachts",
    "Ace Squared",
    "Trac Record",
    "Chai Energy",
    "Novo Holdco",
    "Tap Tap Tap",
    "The Slugger",
    "TIP Imaging",
    "Protein Bar",
    "Section 101",
    "Livin' Lite",
    "Xtreme Labs",
    "Urgent Team",
    "Liber Liber",
    "Rivet Works",
    "Vivid Games",
    "PS Holdings",
    "Score Media",
    "Buzz Monkey",
    "Galaxy Meds",
    "Nexx Studio",
    "Here On Biz",
    "Grow Mobile",
    "Collin Bank",
    "DMO Systems",
    "bnb b",
    "We Yu",
    "Auto i",
    "Neonet",
    "Cell C",
    "Exit 7",
    "C5 Bio",
    "C3 IoT",
    "Web Wi",
    "LBi US",
    "B2 RCP",
    "Club O",
    "PC 911",
    "JMC IT",
    "Aula 7",
    "Feo AR",
    "RBN BV",
    "Get In",
    "Jot It",
    "Comdata",
    "ALG",
    "ARES",
    "U-Start",
    "Primis",
    "MediBic",
    "Kataweb",
    "Malthus",
    "Hotalot",
    "ShoreBank",
    "InfoSpace",
    "Provisur",
    "Scripting",
    "VersaBank",
    "Corillian",
    "Marketwire",
    "DK Organics",
    "UBC Media",
    "Tru Measure",
    "Chase Bank",
    "PBAA",
    "Social Wifi",
    "Advanta",
    "Neoreef",
    "Teleos",
    "Traxys",
    "Mimi's Cafe",
    "Blogter.Hu",
    "Villij",
    "Space-0",
    "New Science",
    "City Screen",
    "Bread Alone",
    "Intelliden",
    "X-Cel India",
    "Larry Welch",
    "Lost Crates",
    "Ag Trucking",
    "Anvis Group",
    "Little Chef",
    "Global Dawn",
    "Captain D's",
    "Crayon Data",
    "Unisource",
    "GrayBoxx",
    "BS PAYONE",
    "Rockstart",
    "RYNO Motors",
    "Data Backup",
    "Potential",
    "Comstar ISA",
    "Logic Spell",
    "N7 Creamery",
    "Beckon Call",
    "Vii Network",
    "Tackle Grab",
    "Daily Joust",
    "When U Wish",
    "Empower STL",
    "Edison Labs",
    "LLS America",
    "Game Minion",
    "Xiabu Xiabu",
    "Monkey Rock",
    "La Mas Mona",
    "Cow Command",
    "Duckie Deck",
    "AsiaTech QC",
    "Colt Group",
    "Paige Denim",
    "Flying Kick",
    "ABA Seguros",
    "Pinion Tech",
    "UV Parnters",
    "Carls Patio",
    "American RV",
    "Connectria",
    "Kira Talent",
    "Level Money",
    "Punch Media",
    "Lean Optima",
    "CREO Agency",
    "Mad Valorem",
    "Custom Easy",
    "Consumer Ed",
    "Liquid Hive",
    "Ovia Health",
    "Planet Leap",
    "FC National",
    "Baby Doctor",
    "Graded Labs",
    "CGL Systems",
    "sEnergy EMS",
    "Duran Audio",
    "Try Bitcoin",
    "Jorden Burt",
    "KW Collards",
    "Sol Tactics",
    "Cosmic Cart",
    "Spectrum FX",
    "Seabury TFX",
    "Warm Health",
    "Trip Finder",
    "CALM Energy",
    "Ruby Macons",
    "ECCO Health",
    "PRISM Group",
    "CATZ Sports",
    "Pinhole Pro",
    "Tista Games",
    "Global Seas",
    "Hat Holding",
    "Mesh Motors",
    "Eat & Smile",
    "Laurus Labs",
    "Three Forks",
    "Fives Group",
    "Crane & Co.",
    "ether books",
    "4M Wireless",
    "CVT Systems",
    "Thirty Five",
    "Baby Carrot",
    "Ember Games",
    "Dairy Queen",
    "OneUp Games",
    "ARC Holding",
    "WeCare Card",
    "Journal Lab",
    "Redmond Pie",
    "Flash Valet",
    "Avid Health",
    "Nara Logics",
    "TAG Medical",
    "Game Nation",
    "Wixel Studi",
    "KULA Causes",
    "Price Stats",
    "Takena Tech",
    "Nuevo Power",
    "PCS Company",
    "James Cable",
    "Aunt Bertha",
    "Spicy Vines",
    "LM Sistemas",
    "Full Access",
    "Vyper Logix",
    "Blue Tomato",
    "11 Plus DIY",
    "Tweet Pivot",
    "The Boombox",
    "Sltt Energy",
    "Texsa India",
    "PRION Group",
    "TNI BioTech",
    "TOP UP",
    "LIW VR",
    "To Be",
    "Tier 3",
    "LG CNS",
    "Mr Doc",
    "Uth TV",
    "Road 9",
    "Do Bem",
    "OK YO",
    "Arkub Group",
    "BLiNQ Media",
    "BIG Cinemas",
    "Swift Setup",
    "Piedmont IT",
    "Guia Vulevu",
    "Annex Cloud",
    "Modern Bank",
    "Beyond Meat",
    "Nordson EDI",
    "TabTor Math",
    "Ochre House",
    "Nu Graphics",
    "Plug in SEO",
    "Social Hour",
    "Dunar Foods",
    "Tower Light",
    "FUSA Global",
    "Grid Sentry",
    "Tokyo Joe's",
    "Zenith Bank",
    "Prestige 96",
    "ESCO Supply",
    "GENCO",
    "Do It",
    "Zen Me",
    "Plan B",
    "B2B TV",
    "3D Geo",
    "VE CRM",
    "5 Bars",
    "redBus",
    "I Play",
    "Fu Hua",
    "JYC VR",
    "IOA Re",
    "IT Nor",
    "SF Bio",
    "EZ Lab",
    "Ion Dx",
    "Dr. Wu",
    "ARM Re",
    "Liv Up",
    "Get Me",
    "Fit Me",
    "Prop X",
    "A Plus",
    "Ener1",
    "Epson",
    "Versant",
    "Arasor",
    "Pironet",
    "Boatyng",
    "HBO",
    "Navico",
    "Sharp",
    "Aquila",
    "Ensogo",
    "Wotnews",
    "CarShop",
    "Agennix",
    "Ice.com",
    "Backplane",
    "US Xpress",
    "Attana",
    "GoGrid",
    "Network",
    "Cinemark",
    "Mimedx",
    "SCO Group",
    "Blueline",
    "Bulbs.com",
    "Fieldglass",
    "Atlassian",
    "BHG Retail",
    "SecureInfo",
    "Tonic",
    "PUNCH Cyber",
    "La Trobe",
    "Mass Metrix",
    "Metrobank",
    "LTG Federal",
    "Safariland",
    "Gen 3 Media",
    "Fatty Group",
    "Religare",
    "WayFinder",
    "Javelin SEF",
    "A. H. Belo",
    "Tastemaker",
    "Satmetrix",
    "TCT Medical",
    "Falls Media",
    "Precede",
    "Lokatech IT",
    "Anew Optics",
    "IT Fidelity",
    "The Gazette",
    "IT Strategy",
    "Zest Airway",
    "Haku Sports",
    "Net Medical",
    "Primo Round",
    "swiss smile",
    "Naked Wines",
    "Curious Hat",
    "Bruce Power",
    "JMG Systems",
    "Altair Prep",
    "Ad Hoc Labs",
    "Skylink LTD",
    "Foobaz Labs",
    "Edgen Group",
    "Rogue Paper",
    "TRU DarkNet",
    "Game Sultan",
    "Bunker Mode",
    "Data Eagles",
    "Data Equity",
    "Astratech",
    "Gmt Group",
    "Von Bismark",
    "Civic Speak",
    "Skynet Labs",
    "ACAT Global",
    "Cooply Apps",
    "Joshua Hong",
    "Field Agent",
    "EcoSmart US",
    "Tracy Press",
    "Lucid Games",
    "G. Ratner D",
    "Red Digital",
    "Ruby Groupe",
    "L2 Surgical",
    "3PD Holding",
    "Fast Drinks",
    "Doctrina U2",
    "Interact CE",
    "Eat Metrics",
    "Label World",
    "Main Office",
    "Close By Me",
    "Gift Boogle",
    "ICU Eyewear",
    "Youmi Media",
    "Uranium One",
    "Fictive Kin",
    "Rig Runners",
    "Enless Soft",
    "My Event DJ",
    "tello Films",
    "Scout Alarm",
    "Inception 3",
    "United Wind",
    "M7 Offshore",
    "Review Adda",
    "Rebel Hippo",
    "SG Meditech",
    "Grid Engine",
    "G2 Mobility",
    "Multi Corp.",
    "Data Gopher",
    "Cyber Sound",
    "Simplex GTP",
    "Yoyo Wallet",
    "PST Tankers",
    "Nu-Med Plus",
    "Corix Group",
    "Mortar Data",
    "Segway City",
    "Nexus Marin",
    "True Drinks",
    "Street King",
    "HUB Seattle",
    "Healthy Mom",
    "Dabo Health",
    "RF Controls",
    "Panax E-TEC",
    "SPARQL City",
    "Catch Stone",
    "Owl Welding",
    "91 Wireless",
    "Quinn Foods",
    "Monet Foods",
    "Next Health",
    "Fox Telecom",
    "T2 Wireless",
    "Beam Dental",
    "Coridea NC1",
    "Alga Energy",
    "Game On 365",
    "Nuro Pharma",
    "Open Energi",
    "Paris Glove",
    "DTS8 Coffee",
    "Social Lair",
    "RA Services",
    "MyCube Safe",
    "Cross Solar",
    "Moxe Health",
    "Third Point",
    "First Tower",
    "GoldMax USA",
    "Mom Trusted",
    "Oski Energy",
    "BOV Holding",
    "3D Robotics",
    "Ether Studi",
    "MMPI Canada",
    "UP Web Game",
    "City Stream",
    "TeamOne LLC",
    "Symbolic IO",
    "Arizona AFO",
    "DONG Energy",
    "ERC (Japan)",
    "C3 Alliance",
    "TRX Futures",
    "WTS Softech",
    "Olaer Group",
    "Maker Media",
    "Devenius PC",
    "Stuzo Group",
    "Myx Fusions",
    "Ekstop Shop",
    "Peek Travel",
    "Open Garden",
    "The OakLabs",
    "UP Solution",
    "ePay Select",
    "VAM SYSTEMS",
    "Time Shrink",
    "Happy Cloud",
    "W3 Networks",
    "SAJE Pharma",
    "PTRL Europe",
    "Iora Health",
    "Thump Games",
    "E Team",
    "Yo GG",
    "I WANT",
    "MBC WB",
    "Mo Jiu",
    "Hut 90",
    "Ash TV",
    "My Sam",
    "Q Bio",
    "EHR Rx",
    "1D Lab",
    "DB Pro",
    "MD Now",
    "Le Sel",
    "No Cow",
    "X BODY",
    "Air HR",
    "e Nova",
    "Mediq",
    "Got It",
    "Baxalta",
    "Nissan",
    "Orrick",
    "Norian",
    "Cigniti",
    "ANEXIO",
    "Myriad",
    "AdaptIT",
    "KA+A",
    "Argnor",
    "Mintel",
    "Logica",
    "Sinnet",
    "DIH",
    "Epsilon",
    "lijit",
    "Mercado",
    "RMS",
    "Radian",
    "SunWize",
    "BDNA",
    "SAE",
    "Veeco",
    "OCLC",
    "Skype",
    "TGM",
    "Meda",
    "Condeco",
    "Addison",
    "Lombard",
    "Kantar",
    "BANSEA",
    "Biocomm",
    "Intelsat",
    "Intechra",
    "BioWorld",
    "Elite",
    "Voivoda",
    "Setanta",
    "Invenda",
    "Medbuy",
    "IVCA",
    "Exclaim",
    "rtraction",
    "NeoWorld",
    "Innolume",
    "AltaVista",
    "Arbor",
    "Nuvio",
    "Avema",
    "Disc Makers",
    "TEOCO",
    "Costa Group",
    "Ardency Inn",
    "Tylr Mobile",
    "Hostway",
    "ViaGen",
    "Marvell",
    "Hocus Locus",
    "Skills Bank",
    "AbD Serotec",
    "Brio Agtech",
    "Advanced Dx",
    "LBS Ukraine",
    "IT Crafters",
    "iPark Valet",
    "Pro Armor",
    "BBCN Bank",
    "Moxie Creek",
    "Refrackt",
    "SANUWAVE",
    "On2.com",
    "Haggar",
    "NextStage",
    "Protemix",
    "marketRx",
    "NimblePros",
    "Blueocean",
    "Vocalocity",
    "Fizzy Lizzy",
    "Gold Violin",
    "Wowjobs.ca",
    "Deep Breeze",
    "SMH Records",
    "Transare",
    "MIT",
    "Compile Net",
    "Maker's Row",
    "OnSite Care",
    "Nico Dekker",
    "Cherry Bird",
    "Focus Media",
    "Spark Rebel",
    "ATM Network",
    "Star One SA",
    "Brake Parts",
    "TeamSystem",
    "TradeKing",
    "CannaScore",
    "Starbreeze",
    "Chat Sports",
    "Net Element",
    "MKK Systems",
    "IES Synergy",
    "Mister Bell",
    "CaerVision",
    "Cirrus Nova",
    "Freedom OSS",
    "InCube Labs",
    "LA City Cab",
    "Qado Energy",
    "Cogent Home",
    "Mixt Greens",
    "Mighty Code",
    "Coming Home",
    "CDL Systems",
    "QPID Health",
    "Mad Rainbow",
    "KSN Hosting",
    "Arecon Data",
    "Fusion Tree",
    "Wisdom TMLC",
    "Pro 3 Games",
    "General LED",
    "Reduce Data",
    "Know Normal",
    "Malvacom AB",
    "DXE Medical",
    "Merge Media",
    "ARMA Energy",
    "Aquilex SRO",
    "Apple Seeds",
    "My Pit Crew",
    "Dot N Pixel",
    "Yi Xuan Ang",
    "Nerd Heroes",
    "Apex Pharma",
    "Grip Agency",
    "Mooff Games",
    "KGH Customs",
    "Datum Logic",
    "User Replay",
    "Dimension X",
    "TM3 Systems",
    "Abel & Cole",
    "Signal Data",
    "Dejero Labs",
    "Prism Money",
    "Avva Health",
    "Axis Health",
    "Cad Teknikk",
    "i7 Networks",
    "Earl Energy",
    "Batavia Air",
    "Ideal Power",
    "Drew Marine",
    "80/20 Group",
    "TVN Systems",
    "Dot Medical",
    "Stem Ciders",
    "EPI GENESYS",
    "DThree Inc.",
    "BK Creative",
    "City Jungle",
    "LoMo Market",
    "SRS Medical",
    "TNO Systems",
    "HON Digital",
    "Baby Jogger",
    "Mobysys Sdn",
    "Miller Dial",
    "solar frost",
    "Blaze Pizza",
    "O2 Insights",
    "Stant Korea",
    "Tie Society",
    "STATS Group",
    "Left Tackle",
    "The Tap Lab",
    "Sharp Dudes",
    "The IT Tree",
    "Adept Cloud",
    "TextUrgy as",
    "Saxis Group",
    "PreCise MRM",
    "PBX Central",
    "MAZ Digital",
    "Talis Group",
    "Reliant CCS",
    "CSS Studios",
    "Life Better",
    "Phase Focus",
    "DPStudio JK",
    "Light Force",
    "4i Security",
    "Relay Foods",
    "Real X Cart",
    "Novus Works",
    "Nox Medical",
    "ABT Medical",
    "Log Insight",
    "MV Sistemas",
    "ella Health",
    "312 Spirits",
    "Great Minds",
    "Saving Fool",
    "eLux Retail",
    "Strom Brand",
    "Raben Media",
    "CASE Design",
    "Drive Power",
    "Linden Care",
    "Citrus Lane",
    "ZD Bottling",
    "ECD Medical",
    "G A Mackman",
    "Wine Doctor",
    "Royal Black",
    "Ruby Ribbon",
    "A10 Capital",
    "Quantum OPS",
    "EV1 Servers",
    "Exego Group",
    "BioQ Pharma",
    "Lost Remote",
    "Dog Digital",
    "Nuru Energy",
    "Diana Group",
    "Game Faster",
    "Mob Science",
    "Citizens Rx",
    "STT Condigi",
    "Howard Weil",
    "Fitch Group",
    "SAMI Health",
    "Xtensive IT",
    "BSN Medical",
    "Daily Juice",
    "Vana Vidyut",
    "Dillon Road",
    "Pattern Tap",
    "Miggle Toys",
    "Verse Studi",
    "Best Energy",
    "The MenView",
    "Thar Energy",
    "VT Services",
    "Shap Mobile",
    "AT Internet",
    "YRFree Labs",
    "Angry Koala",
    "Mind Pirate",
    "OP Software",
    "Equal Earth",
    "Macte! Labs",
    "EW Kaufmann",
    "PROTEUS OCM",
    "SoZo Global",
    "Real Intent",
    "Q Solutions",
    "Julu Mobile",
    "A&A Express",
    "Wowway Labs",
    "Ntreev Soft",
    "CAN Capital",
    "Grupo Xango",
    "Hortor Soft",
    "Ampyx Power",
    "Amiga Games",
    "Addison Lee",
    "The Next Up",
    "XLRant Labs",
    "QE Software",
    "Social Stir",
    "Iconic Labs",
    "Nomad Games",
    "Oyster Dome",
    "Lucky Stars",
    "OTTO Health",
    "QoE Systems",
    "Opts United",
    "Solid Logic",
    "OTR Network",
    "ALEX Brands",
    "Ripple Rock",
    "P2 Security",
    "IDY Academy",
    "Visual Meta",
    "August Home",
    "GROHNO Guss",
    "Funky Moves",
    "Fancy Hands",
    "JHL Biotech",
    "Dental Kidz",
    "CN Creative",
    "Plisch GmbH",
    "Robert MacK",
    "Inner Fence",
    "Rely Energy",
    "Nim Digital",
    "David Fowle",
    "Zoom Audits",
    "Train Times",
    "Dering Hall",
    "SRQ Systems",
    "US Oncology",
    "im3D Clinic",
    "AM Coatings",
    "Cains Foods",
    "ClickN KIDS",
    "Link My Fan",
    "Spano Group",
    "Stray Boots",
    "The Lab Hub",
    "SMD Leisure",
    "EC Solution",
    "Paw Loyalty",
    "Team Gemini",
    "PC Game Bay",
    "Sydney Labs",
    "Seattle 2.0",
    "RBB Bancorp",
    "Duke Street",
    "ASCII Media",
    "Xinya Media",
    "3 In 1 ROOF",
    "Formula One",
    "Rivik Media",
    "Feisty Duck",
    "Fourteen IP",
    "Mister Spex",
    "MOVE Guides",
    "Sweet Tooth",
    "Fix Toolbox",
    "Soul Reborn",
    "Pinnacle 21",
    "Stitch Labs",
    "Game Editor",
    "Levo League",
    "Quick Cable",
    "NEXT Canada",
    "XR Elements",
    "Troax Group",
    "TREE PLANET",
    "Foro Energy",
]
